[workspace]

members = [
    "crates/rstrace",
    "crates/rstrace-cuda-sniff",
]
resolver = "2"

[workspace.dependencies]
rstrace = { path = "crates/rstrace" }
rstrace-cuda-sniff = { path = "crates/rstrace-cuda-sniff", version = "0.6.0" }
anyhow = "1.0.86"
libc = "0.2.139"
