[workspace]

members = [
    "crates/rstrace",
    "crates/rstrace-cuda-sniff",
]
resolver = "2"
default-run = "crates/rstrace"

[workspace.dependencies]
rstrace = { path = "crates/rstrace" }
rstrace-cuda-sniff = { path = "crates/rstrace-cuda-sniff" }
anyhow = "1.0.86"
libc = "0.2.139"
